# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: COMP 110 New and Improved
email: cooperstreiff@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This website presents my EX09 data analysis project for COMP110. The goal of the project is to use anonymized course survey data to identify a possible way to improve the course. My analysis focuses on whether COMP110 should add more low-stakes, quiz-style programming practice for students, especially those with less prior programming experience. I use survey responses about prior programming experience, course difficulty, programming assignment effectiveness, quiz effectiveness, understanding, and course recommendation to explore whether the data supports this idea. The website includes a summary of my reasoning, visualizations created with seaborn, and a conclusion explaining what the data suggests about improving student learning in COMP110.
baseurl: "/improved_course" # the subpath of your site, e.g. /blog
url: "cstreiff7.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  cstreiff7

# Build settings
# Build settings
remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-remote-theme
#- jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
